### ISSUE TITLE
Protected handlers

### ISSUE THREAD

**Issue by reedobrien** [rs/xhandler#10]
Is there an idiomatic way to protect handlers in xhandler or xmux?

There's a handful of ways: wrapping each handler when added to muxer, multiple muxers with different chains, route groups with different chains, using xhandler.If, etc.

Curious if something obvious stands out to you @rs  before I just wrap handlers as necessary....

**Comment by rs** [comment]
What do you mean by protected handler?

**Comment by reedobrien** [comment]
Sorry for the lack of clarity, I mean authn/authz.

**Comment by rs** [comment]
I think depends on your app needs. I see several designs as you mentioned:

- You may just want a middleware which extract auth info when provided and store it in the context so handlers can decide what to do with it.
- You may wrap each handler you want to protect to make sure they are not called if valid credentials aren't supplied, much like the [example provided in xmux README](https://github.com/rs/xmux#basic-authentication).
- You may want to create a sub muxer protected with the same wrapping method that would protect all sub routes under a defined path.

**Comment by reedobrien** [comment]
OK. I'll roll my own;) Just thought it was worth a quick ask.
