### ISSUE TITLE
Have requests use the xhandler context

### ISSUE THREAD

**Issue by kevinconway** [rs/xhandler#15]
I see the comments in https://github.com/rs/xhandler/issues/14 that suggest switching to httprouter after go1.7 because the xhandler features are redundant. I think that's a good way to go, but, given that it takes time to refactor code, I'm wondering if we can make the transition a little easier.

In my case, I have several things running that leverage xhandler and I want to upgrade to go1.7. After the upgrade the rest of the x-libs automatically begin leveraging the new `Request.Context()` for storage and provide new `FromRequest` functions to fetch values. Unfortunately, other code is still using the context given from xhandler which means I have two context objects with different values in them. Any code path that accepts a context object now needs to know if it should be the xhandler context or the request context. If the code needs something from both then I'm broken.

I believe a way to resolve this is to make the `New()` function set the request context to the one generated by xhandler with `r.WithContext(ctx)`. This should not impact any existing functionality while also making the 1.7 upgrade possible without large code refactors. I'll post a PR to illustrate.

**Comment by kevinconway** [comment]
The middleware for close and timeout also operate on the passed in context rather than the request context which falls into the scenario I mentioned. The example patch I posted should account for those issues as well.

**Comment by rs** [comment]
Fixed
