### ISSUE TITLE
What is the best way to have root context with xhandler?

### ISSUE THREAD

**Issue by achiku** [rs/xhandler#7]
Hi, this library looks great, and thank you for open sourcing it! I have a question regarding to so-called root context, which contains values used in any part of existing service (e.g. database connection, or application config).

README and examples describe how to handle request scope context, but I couldn't find a way to integrate root context with application. It could be done by adding a middleware to initialize root context, and put it in the first position of middleware chain, but this method is not really clean since it has to check if key exists in every request.

I might have completely misunderstood what the library provides (maybe it's focusing only on request scope context?), but appreciate any comment. Thaks!

**Comment by achiku** [comment]
The following is what I came up, but not sure if this is the best way.

```go
package main

import (
	"log"
	"net/http"
	"time"

	"github.com/rs/xhandler"
	"golang.org/x/net/context"
)

type initMiddleware struct {
	next xhandler.HandlerC
	ctx  context.Context
}

func (h initMiddleware) ServeHTTPC(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = h.ctx
	h.next.ServeHTTPC(ctx, w, r)
}

func main() {
	ctx := context.Background()
	ctx = context.WithValue(ctx, "key", "global context")
	c := xhandler.Chain{}
	c.UseC(func(next xhandler.HandlerC) xhandler.HandlerC {
		return initMiddleware{
			next: next,
			ctx:  ctx,
		}
	})
	c.UseC(xhandler.CloseHandler)
	c.UseC(xhandler.TimeoutHandler(2 * time.Second))

	xh := xhandler.HandlerFuncC(func(ctx context.Context, w http.ResponseWriter, r *http.Request) {
		value := ctx.Value("key").(string)
		w.Write([]byte("Hello " + value))
	})
	http.Handle("/test", c.Handler(xh))

	if err := http.ListenAndServe(":8080", nil); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by rs** [comment]
You can dot that easily with `c.HandlerCtx()` as follow:

```go
http.Handle("/test", c.HandlerCtx(yourRootCtx, xh))
```

**Comment by achiku** [comment]
That's nice. Thanks!
